name: Check Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled]
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Formatter and Lint Check
    runs-on: ubuntu-latest
    env:
      LINT_MODE: "check"
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install Prettier
        run: npm install --global prettier
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run Lint Script
        run: ./lint.sh --mode=$LINT_MODE
